### ISSUE TITLE
Diode bridge

### ISSUE THREAD

**Issue by SaeidYazdani** [upb-lea/Inkscape_electric_Symbols#10]
A diode bridge would be nice :) I know you can make it from already existing diodes but if possible to have it by default would be great

![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/6137136/0ef03d73-2abe-466e-9ecf-766f511eb921)

**Comment by gituser789** [comment]
Hi,
thanks for this idea.
I currently added it into the main.
![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/62549000/35555070-775f-46e4-a79c-512ebb86b3f7)
