### ISSUE TITLE
Add Ladder Logic Symbols

### ISSUE THREAD

**Issue by flavio20002** [upb-lea/Inkscape_electric_Symbols#11]
**Symbol request**
Ladder logic symbols which are described in IEC 61131-3

**Additional context**
https://www.plcacademy.com/ladder-logic-symbols

If you agree I could add them.

**Comment by gituser789** [comment]
Hi,
i added the symbols. May you can have a look?

**Comment by flavio20002** [comment]
Wonderful, thanks a lot!!
