### ISSUE TITLE
Zener diode

### ISSUE THREAD

**Issue by SengerM** [upb-lea/Inkscape_electric_Symbols#21]
**Symbol request**
A [Zener diode](https://en.wikipedia.org/wiki/Zener_diode).

**Additional context**
You can find the symbols in Inkscape format, ready to be copied, in [my fork](https://github.com/SengerM/Inkscape_electric_Symbols).
![image](https://github.com/user-attachments/assets/72f66c4f-6eac-4b10-bc92-9b33ca04534b)

**Comment by gituser789** [comment]
thx! 
Have added the new variant of Zener diode with commit aaac49977d911486db45288a64fefb12daf9b2b9.
Zener diodes overview:
![image](https://github.com/user-attachments/assets/c0a79127-ca48-42cd-84c0-91ade5fba401)
