### ISSUE TITLE
Add connection terminals

### ISSUE THREAD

**Issue by greenscreenflicker** [upb-lea/Inkscape_electric_Symbols#23]
**Symbol request**
Add connection terminals, say where one can input "Vin"

**Additional context**
Maybe something like this
![grafik](https://github.com/user-attachments/assets/f608d5d9-55ea-4e56-9a91-44f8c4335938)

**Comment by gituser789** [comment]
Thanks for this hint. Will not fix this, as this is easy to draw out of existing components. It will only unnecessarily expand the existing library.

Some hints for your drawing:
The connection points are not perfect in the middle of the crossing lines. May you are not drawing on the grid or not using the snap function of Inkscape? 
With correct settings (see readme file), it should be **very easily** possilbe to draw perfect aligning lines/connection points.
