### ISSUE TITLE
Add optocoupler

### ISSUE THREAD

**Issue by greenscreenflicker** [upb-lea/Inkscape_electric_Symbols#24]
**Symbol request**
Add optocoupler under diode variations (not block symbol)
if possible also a photomos would be cool

**Comment by gituser789** [comment]
Thx, added with 65bbad7f6f582180c29da9f1390221433aae0d59.

![image](https://github.com/user-attachments/assets/5999115f-f9c6-40aa-ac73-72a98e41c016)
