### ISSUE TITLE
Similar resource

### ISSUE THREAD

**Issue by jesuscastane** [upb-lea/Inkscape_electric_Symbols#7]
Hello, 
Thanks for sharing this. 
This youtube video explains how to draw circuits in Inkscape and includes a link to a document with some symbols.

https://www.youtube.com/watch?v=ITpjjDETGk8&t=46s
https://drive.google.com/drive/folders/1f-nZM3DWNn2fsIqcKVvHfLq9PJJ_W-ok

 It might be worth merging the resources. 
Thanks, 
Kind regards,
Jesus

**Comment by gituser789** [comment]
Hi,
thanks for this hint.
I added another PWM signal block.
