### ISSUE TITLE
Make the drawings proper "symbols"

### ISSUE THREAD

**Issue by KronosTheLate** [upb-lea/Inkscape_electric_Symbols#9]
If I open up "Inkscape_Symbols_All" and open the symbols dialog with Ctrl+shift+y, there are no symbols in the current document. However, I can add them with the button in the bottom left of the dialog.
![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/61620837/3fea2f2e-2000-434e-92eb-864c50047dba)

If I do this, and place the file under "home/username/.config/inkscape/symbols", I can then find the file in the symbols menu, and add all the symbols from there, without having copies of all symbols floating around, cluttering my document!
![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/61620837/6768eec8-e3c6-47e8-8796-6b70d1e9b7e8)

So it would be really nice to get all the symbols registered as proper symbols this way, preferably with and without labels. And then typical usage would be to place the file in a file location where inkscape looks for symbols, and to use this menu instead of manually copying the wanted symbols.

**Comment by KronosTheLate** [comment]
An example that I am currently using with some of the most basic things added as symbols can be found in [this file](https://drive.google.com/file/d/1rLEVbrw0WHxMaci4C5bWiJNFaUGVeR2L/view?usp=sharing) on my drive.

Note that the current symbol names are without title. One could add titles, which would make them searchable!

**Comment by gituser789** [comment]
Hi,
can you check this for symbols including markers (arrows), e.g. `potentiometer` and `MOSFET` symbol. In the past, we had some problems with this, so we decided not to make the drawings to `symbols`.

**Comment by gituser789** [comment]
closed due to the mentionend problems and no answer from @KronosTheLate

**Comment by KronosTheLate** [comment]
Sorry about no answer. But yes, the inability to edit the nodes of symbols makes it a bad idea to turn everything into synbols.

**Comment by KronosTheLate** [comment]
There is not much downside to providing the options, so I am very much in favour of that ^_^
Also, un-editable nodes is sometimes not a problem, when just drawing bezier curves between components.

**Comment by gituser789** [comment]
Added some symbols to the `inkscape symbols bar`. They are searchable (see screenshots).
Can you have a look and give some feedback?

![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/62549000/eabe3d88-a209-4479-99dc-32e924bf6347)
![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/62549000/8a8b7935-a89b-47d9-ba14-bfe4111ed4b4)
![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/62549000/d299eae2-0340-47fc-b237-ccfda594d833)
![image](https://github.com/upb-lea/Inkscape_electric_Symbols/assets/62549000/f23fdb3d-1906-43f3-9431-4de752df9067)

**Comment by KronosTheLate** [comment]
That looks great. Hower, I have left my computer behind for the summer, and will not return until september. And I would need that for conveniently testimg. So you will have to a) move on without my input, or b) wait until then. Sorry about any inconvenience.

**Comment by gituser789** [comment]
The symbols are already pushed to the `master`-branch. Nearly all single symbols (except whole schematics like a full LLC-converter and some minor symbols) are available and it is usable from now on.

You can give you feedback once you are back :)

**Comment by KronosTheLate** [comment]
Awesome! Thanks. Knowing myself I will probably remember this the next time i need the symbols, and nobody known when that is. But at some point I will probably check it out again, and try it ^_^

**Comment by gituser789** [comment]
making the symbols to real-inkscape-symbols has some disadvantages in editing them later on.
To edit a symbol, one needs to take them out of the symbols, edit the device (and name it again?) and bring it back to symbols.

I will test this for another while

**Comment by gituser789** [comment]
Any feedback so far? :)
